name: ci

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run generate

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - name: Serve static site
        run: pnpx serve .output/public &

      - name: Wait for server
        run: sleep 3

      - name: Generate PDFs
        run: node scripts/generate-pdf.js
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          PDF_OUTPUT_DIR: ${{ vars.PDF_OUTPUT_DIR }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
